# Generated by Django 3.0.3 on 2020-02-14 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.TextField(max_length=300, verbose_name='адрес')),
                ('year', models.DateTimeField(verbose_name='Дата потсройки')),
            ],
        ),
        migrations.CreateModel(
            name='BrickworkTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bricks_count', models.IntegerField(verbose_name='кол-во кирпичей')),
                ('date', models.DateTimeField(verbose_name='дата кладки')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house_building.House')),
            ],
        ),
    ]
