# Generated by Django 3.0.3 on 2020-02-14 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house_building', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brickworktask',
            options={'verbose_name': 'Задание на кладку', 'verbose_name_plural': 'Задания на кладку'},
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': 'Дом', 'verbose_name_plural': 'Дома'},
        ),
        migrations.RenameField(
            model_name='house',
            old_name='adress',
            new_name='address',
        ),
    ]
